spring:
  datasource:
    driver-class-name: org.h2.Driver
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:h2:mem:sap-sd;DB_CLOSE_DELAY=-1;MODE=MySQL

  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console

  sql:
    init:
      platform: mysql
      schema-locations: classpath:h2sql/sap-sd_schema.sql
      data-locations: classpath:h2sql/sap-sd_data.sql

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
